Rust 没有异常系统。Rust 将错误分为两类：**可恢复的**（*recoverable*）和 **不可恢复的**（*unrecoverable*）。
可恢复的错误例如文件未找到。不可恢复的错误如下标越界，这往往是出现bug的征兆。
Rust 用 `Result<T, E>` 类型处理可恢复的错误，用 `panic!` 宏在遇到不可恢复的错误时停止执行。

## `panic!`

出现 `panic!` 时，程序默认会进行**展开**（*unwinding*），即回溯和清理栈上的数据。另外也可以选择直接终止（abort）程序。在 `Cargo.toml` 的 `[profile]` 部分添加 `panic = 'about'` 即可采用终止方式。

设置 `RUST_BACKTRACE=1` 环境变量后即可查看发生 panic 的函数调用回溯。

## `Result`

```rust
enum Result<T, E> {
	Ok(T),
    Err(E),
}
```

可以使用 match 来处理，例如：

```rust
let f = match File::open("hello.txt") {
    Ok(f) => f,
    Err(e) => panic!("{:?}", e),
};
```

可以用 `Result` 上的 `unwrap` 函数处理，如果 `Result` 是 `Ok`，`unwrap` 返回其中的值，否则调用 `panic!`。`expect` 函数与 `unwrap` 类似，不过可以指定报错信息：

```rust
let mut f = File::open("hello.txt").unwrap();
let mut f = File::open("hello.txt").expect("Failed to open hello.txt");
```

#### 错误传播

在函数中遇到错误，将其传递给上层调用者是一种常见的操作。一种直观的写法是使用 `match`：

```rust
fn read_file_into_string() -> Result<String, io::Error> {
    let mut f = match File::open("hello.txt") {
        Ok(f) => f,
        Err(e) => return Err(e),
    };
    let mut s = String::new();
    match f.read_to_string(&mut s) {
        Ok(_) => Ok(s),
        Err(e) => return Err(e),
    }
}
```

为了减少样板代码，可以使用 `?` 运算符，其作用与上面的 `match` 相同：

```rust
fn read_file_into_string() -> Result<String, io::Error> {
    let mut f = File::open("hello.txt")?;
    let mut s = String::new();
    f.read_to_string(&mut s)?;
    Ok(s)
}
```

还可以通过链式调用，使代码更简洁：

```rust
fn read_file_into_string() -> Result<String, io::Error> {
    let mut s = String::new();
    File::open("hello.txt")?.read_to_string(&mut s)?;
    Ok(s)
}
```

另外，`?` 运算符也可以用在 `Option` 上。

#### `main` 函数

`main` 函数的返回值可以是 `Result<(), Box<dyn std::error::Error>>`，这就允许 `main` 函数返回错误。可执行程序最终会向操作系统返回合适的整数。